name: CD Docker

on:
  push:
    branches:
      - 'push-docker'
      - '*-hotfix'

env:
  DEFAULT_TAG_VERSION: "v1-latest"
  DOCKER_REPO_NAME: "backenddevelopersltd/bittensor-pylon"

permissions:
  contents: read

jobs:
  docker-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Set TAG_VERSION based on branch
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME}"
          if [[ "$BRANCH_NAME" == *-hotfix ]]; then
            TAG_VERSION="$BRANCH_NAME"
          else
            TAG_VERSION="${DEFAULT_TAG_VERSION}"
          fi
          echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO_NAME }}:${{ env.TAG_VERSION }}
            ${{ env.DOCKER_REPO_NAME }}:git-${{ github.sha }}
